apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    service: backend
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - port: 3001
---
## DEPLOY
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: fyp-backend-container
        image: hakeem99/backend
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: pgsecret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: pgsecret
              key: password
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: pgsecret
              key: host
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: pgsecret
              key: port
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: pgsecret
              key: database
        - name: DATABASE_URI
          valueFrom:
            configMapKeyRef:
              name: pgsecret
              key: uri
        ports:
        - containerPort: 3001